github_actions:
- .github/**/*

test:
- test/**/*
- test/api_getTaxonomyPackagingMaterialsServer_test.dart
- test/api_getTaxonomyPackagingShapesServer_test.dart

knowledge panels:
- lib/model/knowledge_panel.g.dart
- lib/model/knowledge_panel_element.g.dart

product:
- lib/model/product.dart
- lib/model/product.g.dart

robotoff:
- lib/model/robotoff_question.g.dart

pubspec:
- pubspec.yaml

ecoscore:
- lib/model/ecoscore_data.g.dart

personalized search:
- lib/personalized_search/**/*

folksonomy:
- lib/folksonomy.dart

packaging:
- lib/model/TaxonomyPackagingMaterial.dart
- lib/model/TaxonomyPackagingMaterial.g.dart
- lib/model/TaxonomyPackagingShape.dart
- lib/model/TaxonomyPackagingShape.g.dart
- test/api_getTaxonomyPackagingMaterialsServer_test.dart
- test/api_getTaxonomyPackagingShapesServer_test.dart
