github_actions:
- .github/**/*

test:
- test/**/*
- test/api_getTaxonomyPackagingMaterialsServer_test.dart
- test/api_getTaxonomyPackagingShapesServer_test.dart

knowledge panels:
- lib/model/KnowledgePanel.g.dart
- lib/model/KnowledgePanelElement.g.dart

product:
- lib/model/Product.dart
- lib/model/Product.g.dart

robotoff:
- lib/model/RobotoffQuestion.g.dart

pubspec:
- pubspec.yaml

ecoscore:
- lib/model/EcoscoreData.g.dart

personalized search:
- lib/personalized_search/**/*

folksonomy:
- lib/folksonomy.dart

packaging:
- lib/model/TaxonomyPackagingMaterial.dart
- lib/model/TaxonomyPackagingMaterial.g.dart
- lib/model/TaxonomyPackagingShape.dart
- lib/model/TaxonomyPackagingShape.g.dart
- test/api_getTaxonomyPackagingMaterialsServer_test.dart
- test/api_getTaxonomyPackagingShapesServer_test.dart
